name: Remove lines ending with ;N
on:
  push:
    branches:
      - main
jobs:
  remove-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Remove lines with ;N at end
        run: |
          grep -rlE '.*;N\s*$' . | while read file; do
            sed -i.bak -E '/.*;N\s*$/d' "$file" && rm "$file.bak"
          done
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Remove lines ending with ;N" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
